export const MOVE_CHARACTER_UP = "MOVE_CHARACTER_UP";
export const MOVE_CHARACTER_RIGHT = "MOVE_CHARACTER_RIGHT";
export const MOVE_CHARACTER_DOWN = "MOVE_CHARACTER_DOWN";
export const MOVE_CHARACTER_LEFT = "MOVE_CHARACTER_LEFT";

export const WHILE_WALKING = "WHILE_WALKING";
export const STOP_WALKING = "STOP_WALKING";

export const CANNOT_WALK = "CANNOT_WALK";